### ISSUE TITLE
IsPlayerInWaterEx

### ISSUE THREAD

**Issue by Pa4enka** [AmyrAhmady/CreateWater#1]
Why not?
```
stock IsPlayerInWaterEx(playerid)
{
    return playerWater[playerid][playerWaterID] > -1 ? (1) : (0);
}
```

**Comment by AmyrAhmady** [comment]
@Pa4enka Actually , I kinda don’t like that type of statements , It makes me feel like my code is not clear. Btw , will change for next update as you wish . Thanks!
